@startuml
'https://plantuml.com/component-diagram

actor user

package "exposed services" {
    [Frontend]
    [api]
    [print]
}

package "internal services" {
    [browserless]
    database "database"
}

user --> [Frontend]
[Frontend] --> [api]
[Frontend] --> [print]
[print] --> [api]
[api] --> "database"
[print] <--> [browserless]




@enduml